name: Recon-Ultimate-Monitoring

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  recon-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Hunting Tools
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/katana/cmd/katana@latest
          go install github.com/lc/gau/v2/cmd/gau@latest
          go install -v github.com/tomnomnom/anew@latest
          go install -v github.com/projectdiscovery/notify/cmd/notify@latest
          go install github.com/003random/getJS/v2@latest
          pip install uro
          echo "/home/runner/go/bin" >> $GITHUB_PATH

      - name: Configure API Keys & Discord
        env:
          SUBFINDER_CONFIG: ${{ secrets.SUBFINDER_CONFIG }}
          NOTIFY_CONFIG: ${{ secrets.NOTIFY_CONFIG }}
        run: |
          # إعداد ملفات التكوين في مساراتها الصحيحة
          mkdir -p ~/.config/subfinder/
          mkdir -p ~/.config/notify/
          echo "$SUBFINDER_CONFIG" > ~/.config/subfinder/provider-config.yaml
          echo "$NOTIFY_CONFIG" > ~/.config/notify/provider-config.yaml

      - name: Run Recon
        run: |
          chmod +x recon.sh
          ./recon.sh .

      - name: Save State to GitHub
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Recon-Bot"
          git add all-domains.txt all_live_urls.txt FINAL_JS_ENDPOINTS.txt js_history_metadata.txt
          git commit -m "Update Recon Database [skip ci]" || echo "No changes"
          git push
